config/routes.rb
BackBurner::Application.routes.draw do
  devise_for :cooks, controllers: { sessions: 'sessions' }
  devise_for :chefs, controllers: { sessions: 'sessions' }

  root "welcome#index"

  resources :posts, only: [:index, :new, :create, :update] do
    resources :signups, only: [:create]
  end

  resources :chefs, only: [:show]

  resources :cooks, only: [:show]

  resources :signups do
    post 'accept'
    post 'reject'
  end

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_address
    "#{address} #{city}, #{state} #{zip}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def text_chef(signup)
    number = phone_number
    twilio_client = Twilio::REST::Client.new(ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"])
    binding.pry
    twilio_client.account.messages.create(
      from: ENV['TWILIO_PHONE_NUMBER'],
      to: number,
      body: "#{signup.cook.full_name} has signed up for one of your job posts! https://backburner.herokuapp.com/"
    )
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :restaurant_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/controllers/Chef/confirmations_controller.rb
class Chef::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Chef/omniauth_callbacks_controller.rb
class Chef::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Chef/passwords_controller.rb
class Chef::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Chef/registrations_controller.rb
class Chef::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    binding.pry
    # these_params = params[:chef]
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Welcome Chef! You have signed up successfully."
    else
      render :new
    # super
    end
  end

  private

  def chef_params
    params.require(:chef).permit(:first_name, :last_name, :email, :restaurant_name, :address, :city, :state, :zip, :phone_number, :description, :password, :password_confirmation)
  end



  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :restaurant_name, :address, :city, :state, :zip, :phone_number, :description, :password, :password_confirmation)}
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Chef/sessions_controller.rb
class Chef::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/Chef/unlocks_controller.rb
class Chef::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/chefs/show.html.erb
<h1>Welcome back, <%= @chef.first_name %></h1>

<h3>Your job posts:</h3>
  <div class="row">
    <div class="small-2 large-4 columns">Date</div>
    <div class="small-2 large-4 columns">Start Time</div>
    <div class="small-2 large-4 columns">End Time</div>
    <div class="small-2 large-4 columns">Hourly Wage</div>
    <div class="small-2 large-4 columns">Description</div>
  </div>
  <% @posts.each do |post| %>
    <div class="row">
      <div class="small-2 large-4 columns"><%= post.date %></div>
      <div class="small-2 large-4 columns"><%= post.start_time %></div>
      <div class="small-2 large-4 columns"><%= post.end_time %></div>
      <div class="small-2 large-4 columns"><%= post.wage %></div>
      <% if post.description.blank? %>
        <div class="small-2 large-4 columns">None Provided</div>
      <% else %>
        <div class="small-2 large-4 columns"><%= post.description %></div>
      <% end %>
    </div>
    <% post.signups.each do |signup| %>
      <div id= <%= signup.cook_id %>
        <div class="row">
          <div class="small-2 large-4 columns"><%= signup.cook.full_name %></div>
          <% if signup.cook.description.blank? %>
            <div class="small-2 large-4 columns">None Provided</div>
          <% else %>
            <div class="small-2 large-4 columns"><%= signup.cook.description %></div>
          <% end %>
          <% if signup.decision == "Pending" %>
            <div class="small-1 columns"><%= button_to "Accept", signup_accept_path(signup), method: :post %></div>
            <div class="small-1 columns"><%= button_to "Reject", signup_reject_path(signup), method: :post %></div>
          <% else %>
            <%= signup.decision %>
          <% end %>
          </div>
        <% end %>
      </div>
  <% end %>

  <%= button_to "Create New Job Post", new_post_path, method: :get %>