config/routes.rb
BackBurner::Application.routes.draw do
  devise_for :cooks, controllers: { sessions: 'sessions' }
  devise_for :chefs, controllers: { sessions: 'sessions' }

  root "welcome#index"

  resources :posts, only: [:index, :new, :create, :update] do
    resources :signups, only: [:create]
  end

  resources :chefs, only: [:show]

  resources :cooks, only: [:show]

  resources :signups do
    post 'accept'
    post 'reject'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :chef
  has_many :signups, dependent: :destroy
  has_many :cooks, through: :signups

  validates :chef, presence: true
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :wage, presence: true

  # def selected_cook
  #   self.cooks.where(selected = true)
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_chef!, only: [:create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "New job post created!"
      redirect_to posts_path
    else
      flash[:error] = @post.errors.full_messages.join(", ")
      redirect_to posts_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :date,
      :start_time,
      :end_time,
      :wage,
      :description
    ).merge(chef: current_chef)
  end

end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :start_time, "Start Time"%><br />
    <%= f.text_field :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time, "End Time"%><br />
    <%= f.text_field :end_time %>
  </div>

  <div class="field">
    <%= f.label :wage, "Hourly Wage" %><br />
    <%= f.text_field :wage %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Update Job Post Details!</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1> Job Posts! </h1>

<ul class="accordion" data-accordion>
  <% @posts.each do |post| %>
    <li class="accordion-item" data-accordion-item>
      <a href="#"> <%= post.chef.restaurant_name %></a>
        <div class="accordion-content" data-tab-content >
          <div class="row">
            <div class="small-1 columns">Address</div>
            <div class="small-1 columns">Date</div>
            <div class="small-1 columns">Start Time</div>
            <div class="small-1 columns">End Time</div>
            <div class="small-1 columns">Hourly Wage</div>
            <div class="small-1 columns">Description</div>
          </div>

          <div class="row">
            <div class="small-1 columns"><%= post.chef.full_address %></div>
            <div class="small-1 columns"><%= post.date %></div>
            <div class="small-1 columns"><%= post.start_time %></div>
            <div class="small-1 columns"><%= post.end_time %></div>
            <div class="small-1 columns"><%= post.wage %></div>
            <% if post.description.blank? %>
              <div class="small-1 columns">None Provided</div>
            <% else %>
              <div class="small-1 columns"><%= post.description %></div>
            <% end %>
            <% if cook_signed_in? && !post.cooks.include?(current_cook) %>
              <div class="small-1 columns"><%= button_to "Sign Up", post_signups_path(post), method: :post %></div>
            <% end %>
          </div>
        </div>
        <% end %>
      </li>
</ul>

<% if chef_signed_in? %>
  <%= button_to "Create New Job Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>